### PR TITLE
modernize according to buildout.plonetest README

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by gotcha** [comment]
@mauritsvanrees This is also a step forward for #6. In order for the corresponding branch in `buildout.plonetest` to be inline with documentation.

**Review by mauritsvanrees — APPROVED** [review]
Seems to work. I guess this PR is replaced by PR #7.  But if you think it helps, you can merge this one first.

**Comment by mauritsvanrees** [comment]
Do you have any idea why https://travis-ci.org/collective/collective.noindexing is empty? It seems like no jobs have ever been run, but that is obviously not true.

**Comment by gotcha** [comment]
I have no idea. Could be a bug related to using the version field of `.travis.yml`

**Comment by gotcha** [comment]
@mauritsvanrees 
Actually, if you go to travis-ci.com, all previous builds are still there : https://travis-ci.com/collective/collective.noindexing/builds. 
On travis-ci.org, there is only the one I just triggered. https://travis-ci.org/collective/collective.noindexing/builds

**Comment by gotcha** [comment]
I have filed a support ticket on Travis

**Comment by gotcha** [comment]
@mauritsvanrees 

This is what I got from Travis support:

> We currently trying to migrate all repositories from .ORG to .COM but if you still have repository only exist on .ORG it is also possible that you see those builds only .ORG.

AFAIU, we should use .com from now on...

**Pull request merged**
